
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEP CLOSEROW CLOSESPAN CLOSESTYLE CLOSETABLE CONTENT END GARBAGE OPENDATA OPENDIV OPENHEADER OPENHREF OPENP OPENROW OPENSPAN OPENSTYLE OPENTABLEstart : tableskiptag : CONTENT skiptag empty\n               | OPENHREF skiptag\n               | CLOSEHREF skiptag\n               | OPENP skiptag\n               | CLOSEP skiptag\n               | emptytable : BEGINTABLE skiptag ENDempty :content : CONTENT\n               | empty'
    
_lr_action_items = {'BEGINTABLE':([0,],[3,]),'$end':([1,2,11,],[0,-1,-8,]),'CONTENT':([3,5,7,8,9,10,],[5,5,5,5,5,5,]),'OPENHREF':([3,5,7,8,9,10,],[7,7,7,7,7,7,]),'CLOSEHREF':([3,5,7,8,9,10,],[8,8,8,8,8,8,]),'OPENP':([3,5,7,8,9,10,],[9,9,9,9,9,9,]),'CLOSEP':([3,5,7,8,9,10,],[10,10,10,10,10,10,]),'END':([3,4,5,6,7,8,9,10,12,13,14,15,16,17,],[-9,11,-9,-7,-9,-9,-9,-9,-9,-3,-4,-5,-6,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'table':([0,],[2,]),'skiptag':([3,5,7,8,9,10,],[4,12,13,14,15,16,]),'empty':([3,5,7,8,9,10,12,],[6,6,6,6,6,6,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> table','start',1,'p_start','module2.1.py',122),
  ('skiptag -> CONTENT skiptag empty','skiptag',3,'p_skiptag','module2.1.py',127),
  ('skiptag -> OPENHREF skiptag','skiptag',2,'p_skiptag','module2.1.py',128),
  ('skiptag -> CLOSEHREF skiptag','skiptag',2,'p_skiptag','module2.1.py',129),
  ('skiptag -> OPENP skiptag','skiptag',2,'p_skiptag','module2.1.py',130),
  ('skiptag -> CLOSEP skiptag','skiptag',2,'p_skiptag','module2.1.py',131),
  ('skiptag -> empty','skiptag',1,'p_skiptag','module2.1.py',132),
  ('table -> BEGINTABLE skiptag END','table',3,'p_table','module2.1.py',137),
  ('empty -> <empty>','empty',0,'p_empty','module2.1.py',144),
  ('content -> CONTENT','content',1,'p_content','module2.1.py',148),
  ('content -> empty','content',1,'p_content','module2.1.py',149),
]
