
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSEDIV CLOSEHEADER CLOSEHREF CLOSEROW CLOSESPAN CLOSESUP CLOSETABLE CONTENT GARBAGE OPENBODY OPENDATA OPENDIV OPENHEADER OPENHREF OPENROW OPENSPAN OPENSUP OPENTABLEstart : BEGINTABLE skipall OPENBODY body body : handlerow handlerow : skip OPENROW handlecontent CLOSEROW handlerow\n                 | skip handlecontent : skip OPENDATA handledata CLOSEDATA handlecontent\n                     | skip skipall : CONTENT skipall\n               | GARBAGE skipall\n               | OPENROW skipall\n               | CLOSEROW skipall\n               | OPENHEADER skipall \n               | CLOSEHEADER skipall\n               | handledata : CONTENT \n                  | CONTENT GARBAGE CONTENT GARBAGE CONTENT\n                  | CONTENT GARBAGE GARBAGE CONTENT\n                  | OPENHREF CONTENT CLOSEHREF\n                  | OPENSPAN CONTENT CLOSESPAN\n                  | OPENHREF CONTENT CLOSEHREF CONTENT\n                  | OPENHREF CONTENT CONTENT CONTENT CLOSEHREF\n                  | CONTENT CONTENT\n                  | skip : CONTENT skip\n            | GARBAGE skip\n            | '
    
_lr_action_items = {'BEGINTABLE':([0,],[2,]),'$end':([1,10,17,18,19,20,21,23,24,28,33,],[0,-25,-1,-2,-4,-25,-25,-23,-24,-25,-3,]),'CONTENT':([2,4,5,6,7,8,9,10,20,21,22,27,28,30,31,32,34,36,37,41,42,43,45,],[4,4,4,4,4,4,4,20,20,20,20,30,20,35,37,38,20,40,42,46,47,48,49,]),'GARBAGE':([2,4,5,6,7,8,9,10,20,21,22,28,30,34,36,40,],[5,5,5,5,5,5,5,21,21,21,21,21,36,21,41,45,]),'OPENROW':([2,4,5,6,7,8,9,10,19,20,21,23,24,28,],[6,6,6,6,6,6,6,-25,22,-25,-25,-23,-24,-25,]),'CLOSEROW':([2,4,5,6,7,8,9,20,21,22,23,24,25,26,34,39,],[7,7,7,7,7,7,7,-25,-25,-25,-23,-24,-6,28,-25,-5,]),'OPENHEADER':([2,4,5,6,7,8,9,],[8,8,8,8,8,8,8,]),'CLOSEHEADER':([2,4,5,6,7,8,9,],[9,9,9,9,9,9,9,]),'OPENBODY':([2,3,4,5,6,7,8,9,11,12,13,14,15,16,],[-13,10,-13,-13,-13,-13,-13,-13,-7,-8,-9,-10,-11,-12,]),'OPENDATA':([20,21,22,23,24,25,34,],[-25,-25,-25,-23,-24,27,-25,]),'OPENHREF':([27,],[31,]),'OPENSPAN':([27,],[32,]),'CLOSEDATA':([27,29,30,35,43,44,46,48,49,50,],[-22,34,-14,-21,-17,-18,-16,-19,-15,-20,]),'CLOSEHREF':([37,47,],[43,50,]),'CLOSESPAN':([38,],[44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'skipall':([2,4,5,6,7,8,9,],[3,11,12,13,14,15,16,]),'body':([10,],[17,]),'handlerow':([10,28,],[18,33,]),'skip':([10,20,21,22,28,34,],[19,23,24,25,19,25,]),'handlecontent':([22,34,],[26,39,]),'handledata':([27,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> BEGINTABLE skipall OPENBODY body','start',4,'p_start','extract_data.py',102),
  ('body -> handlerow','body',1,'p_body','extract_data.py',105),
  ('handlerow -> skip OPENROW handlecontent CLOSEROW handlerow','handlerow',5,'p_handlerow','extract_data.py',108),
  ('handlerow -> skip','handlerow',1,'p_handlerow','extract_data.py',109),
  ('handlecontent -> skip OPENDATA handledata CLOSEDATA handlecontent','handlecontent',5,'p_handlecontent','extract_data.py',111),
  ('handlecontent -> skip','handlecontent',1,'p_handlecontent','extract_data.py',112),
  ('skipall -> CONTENT skipall','skipall',2,'p_skipall','extract_data.py',116),
  ('skipall -> GARBAGE skipall','skipall',2,'p_skipall','extract_data.py',117),
  ('skipall -> OPENROW skipall','skipall',2,'p_skipall','extract_data.py',118),
  ('skipall -> CLOSEROW skipall','skipall',2,'p_skipall','extract_data.py',119),
  ('skipall -> OPENHEADER skipall','skipall',2,'p_skipall','extract_data.py',120),
  ('skipall -> CLOSEHEADER skipall','skipall',2,'p_skipall','extract_data.py',121),
  ('skipall -> <empty>','skipall',0,'p_skipall','extract_data.py',122),
  ('handledata -> CONTENT','handledata',1,'p_handledata','extract_data.py',139),
  ('handledata -> CONTENT GARBAGE CONTENT GARBAGE CONTENT','handledata',5,'p_handledata','extract_data.py',140),
  ('handledata -> CONTENT GARBAGE GARBAGE CONTENT','handledata',4,'p_handledata','extract_data.py',141),
  ('handledata -> OPENHREF CONTENT CLOSEHREF','handledata',3,'p_handledata','extract_data.py',142),
  ('handledata -> OPENSPAN CONTENT CLOSESPAN','handledata',3,'p_handledata','extract_data.py',143),
  ('handledata -> OPENHREF CONTENT CLOSEHREF CONTENT','handledata',4,'p_handledata','extract_data.py',144),
  ('handledata -> OPENHREF CONTENT CONTENT CONTENT CLOSEHREF','handledata',5,'p_handledata','extract_data.py',145),
  ('handledata -> CONTENT CONTENT','handledata',2,'p_handledata','extract_data.py',146),
  ('handledata -> <empty>','handledata',0,'p_handledata','extract_data.py',147),
  ('skip -> CONTENT skip','skip',2,'p_skip','extract_data.py',184),
  ('skip -> GARBAGE skip','skip',2,'p_skip','extract_data.py',185),
  ('skip -> <empty>','skip',0,'p_skip','extract_data.py',186),
]
